name: Generate Snake

on:
  schedule: # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o conteúdo do seu repositório
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Gera a cobra
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg

      # Adiciona e faz o push do SVG gerado
      - name: Push Snake to the output branch
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated Snake"
          git push origin HEAD:output --force
